### ISSUE TITLE
[teleinfo] frame reception crash with "Got I/O exception 'Underlying input stream returned zero bytes' during receiving. exiting thread." error

### ISSUE THREAD

**Issue by nokyyz** [nokyyz/openhab2-addons#7]
## Expected Behavior
No crash

## Current Behavior
After about 7 days since the last OH start (last OH start : july 16, 2019 at 15:13), the Teleinfo binding has stop to receive Teleinfo frames from GCE USB module with the following exception:

> 2019-07-23 07:08:56.170 [ERROR] [nternal.serial.TeleinfoReceiveThread] - Got I/O exception 'Underlying input stream returned zero bytes' during receiving. exiting thread.

This exception has been throwed when HC/HP switch (**7:08** AM in my case).

I have already noticed this problem a few days ago: Teleinfo binding started at july 12, 2019 at 19:59 and crash at july 16, 2019 at **07:08** AM

Remark: GCE USB module was linked to /dev/ttyUSB1 file in the OS. At the time of the crash, a new DEV file has been created (/dev/ttyUSB2) and the /dev/ttyUSB1 file does not exist anymore:

> $ ls -l /dev/ttyUS*
> crw------- 1 root root 188, 0 Jul 16 11:27 /dev/ttyUSB0
> crw-rw-rw- 1 root root 188, 2 Jul 23 07:08 /dev/ttyUSB**2**

## Possible Solution
To implement a retry mechanism ?
Hardware issue from GCE USB module ?

## Your Environment
* OpenHAB 2.5.0-M1 and Teleinfo addon alpha-20190716-1440 version)
* Synology DSM, Docker, official OpenHAB docker image

**Comment by nokyyz** [comment]
New crash ! Teleinfo binding started at july 23, 2019 at 23:13 and crash at august 6, 2019 at 07:08 AM (HC/HP switch).

After this new crash, I'm searching the cause of this crash (hardware or software ?). 
To detect a possible hardware issue, I have created a basic Linux script to dump into a file all Teleinfo frames:
dump-teleinfo.sh file
```
#!/bin/bash
cat /dev/ttyUSB2 > /tmp/teleinfo/cat-teleinfo.txt
```

... and run in background this script (`nohup dump-teleinfo.sh`)
Remark: before to run the script, the serial port must be parameterized like this:
`stty -F /dev/ttyUSB2 1200 sane evenp parenb cs7 -crtscts`

Wait & see

Important note: my GCE USB module is connected to the only USB2 port of my Synology 415+... (others USB devices are connected to USB3 ports)

**Comment by nokyyz** [comment]
News...
Since August 18, 2019 at 07:08 AM, the 

> cat-teleinfo.txt

 file is not ever updated !
x@x:/tmp/teleinfo$ ls -l
total 49168
-rw-r--r-- 1 root root 50340805 Aug 18 07:08 cat-teleinfo.txt
-rwxr-xr-x 1 root root       62 Aug 12 19:23 dump-teleinfo.sh
-rw------- 1 root root        0 Aug 12 19:25 nohup.out

**Comment by nokyyz** [comment]
New test with GCE USB module connected to an USB3 port is working progress...

**Comment by ghys** [comment]
I can confirm this error also occurs with a Cartelectronic USB modem (https://www.cartelectronic.fr/teleinfo-compteur-enedis/127-teleinfo-1-compteur-usb-lc.html), about 2 or 3 times a day.
Restarting the bundle with the openHAB console fixes the problem. A retry mechanism as suggested in #9 might do the trick, it doesn't matter if those errors occur as long as the binding recovers from them.

**Comment by nokyyz** [comment]
A new Retry mechanism has been implemented in https://github.com/nokyyz/openhab2-addons/releases/tag/beta-20191029-2235 version:

Some details:
- on invalid frame error: the binding skips invalid frame and goes to the next frame
- on timeout error: the binding waits 60 seconds and resumes the frame reading
- on I/O error: the binding closes the serial port and reopen it within 60 seconds
