### ISSUE TITLE
threepase energy-meter not working

### ISSUE THREAD

**Issue by pakutz79** [nokyyz/openhab2-addons#8]
While reading data form a threephase energy-meter the import of the serial-frame stop at **groupLine = IINST1 002 J**

Read objects:
ADCO        700809411771 
OPTARIF     EJP.
ISOUSC      30 
EJPHN        059027424 
EJPHPM     003795726
PTEC          HN
IINST1        002
IINST2        002
IINST3        000
IMAX1       025
IMAX2       021
IMAX3       019
PMAX        08810
PAPP          00880
MOTDETAT 000000
PPOT          00

**Comment by nokyyz** [comment]
Feature (three-phased electricity meters) implemented in Alpha-20191015-1958 version
