### ISSUE TITLE
[teleinfo] try to recover from errors

### ISSUE THREAD

**Issue by ghys** [nokyyz/openhab2-addons#9]
## Expected Behavior
When any kind of error occurs with the data reception, the binding should try to recover from it.

## Current Behavior
The thread is exited after an error (this is explicitely mentioned in the error message) and then no data is received; but it works again if the binding is restarted.

## Possible Solution
Since it works again after a bundle restart, it means it isn't a hardware crash and the error can probably be recovered from. Maybe a simple retry mechanism after an error occurs (close/reopen the port, spawn another thread?) could make sure the binding continues working unattended (i.e. without being restarted). It doesn't matter if there a little gap of a few seconds in the data as long as it comes back.

## Steps to Reproduce (for Bugs)
Keep the binding running until an reception error occurs.

## Your Environment
openHAB 2.5.0.M4 / Oracle Java 8 / PINE A64 / Debian Buster with Armbian Linux 4.19.59-sunxi64

**Comment by nokyyz** [comment]
Fixed in https://github.com/nokyyz/openhab2-addons/releases/tag/beta-20191029-2235 version
